// © 2026 Vitaly Gitelman. All Rights Reserved.
// =============================================================================
// generate_answer_key.js — One-time script to extract correct answers from
// questions.js (and translation files) into an Apps Script .gs source file.
//
// Usage:
//   node deployment/generate_answer_key.js
//
// Output:
//   deployment/answer_key.gs   (paste this as a NEW file in your Apps Script
//                               project, alongside external_exam_apps_script.js)
//
// What it does:
//   - Reads questions.js, decodes each question's correct answer index
//     (correct = ci ^ (id % 256)).
//   - Optionally reads translation files (questions_en.js, etc.) and extracts
//     per-language correct indices (translations have their own ci because
//     answer wording — and thus answer order — may differ).
//   - Emits ANSWER_KEY_BY_LANG: { he: {id: idx}, ru: {...}, en: {...}, ... }.
//
// Re-run this whenever questions.js changes. Then re-deploy the Apps Script.
// =============================================================================
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');

function loadAsVar(filename, varName) {
  const fullPath = path.join(ROOT, filename);
  if (!fs.existsSync(fullPath)) {
    console.warn('[skip] missing file: ' + filename);
    return null;
  }
  const source = fs.readFileSync(fullPath, 'utf8');
  const sandbox = {};
  // Shim browser globals so files that do `window.QUESTIONS = ...` don't crash.
  sandbox.window = sandbox;
  sandbox.self = sandbox;
  sandbox.globalThis = sandbox;
  vm.createContext(sandbox);
  vm.runInContext(source, sandbox, { filename, timeout: 30000 });
  const value = sandbox[varName];
  if (value === undefined) {
    throw new Error('Variable ' + varName + ' not found in ' + filename);
  }
  return value;
}

function decodeCI(ci, id) { return ci ^ (id % 256); }

// === Hebrew (and any non-translated languages mixed in) ===
console.log('Loading questions.js ...');
const questions = loadAsVar('questions.js', 'QUESTIONS');
console.log('  ' + questions.length + ' questions loaded');

const keys = { he: {}, ru: {} };
let heCount = 0, ruCount = 0;
for (const q of questions) {
  if (typeof q.id !== 'number' || typeof q.ci !== 'number') {
    console.warn('  [warn] skipping question without id/ci: ' + JSON.stringify(q).slice(0, 80));
    continue;
  }
  const correct = decodeCI(q.ci, q.id);
  if (correct < 0 || correct > 9) {
    console.warn('  [warn] question ' + q.id + ' has implausible correct=' + correct);
    continue;
  }
  // Russian-original questions are tagged language: 'ru'; everything else goes
  // to Hebrew (the canonical answer set most of the system uses).
  if (q.language === 'ru') {
    keys.ru[q.id] = correct;
    ruCount++;
  } else {
    keys.he[q.id] = correct;
    heCount++;
  }
}
console.log('  he entries: ' + heCount);
console.log('  ru (original) entries: ' + ruCount);

// === Translation files: each has its own ci per question ===
const translationFiles = [
  { file: 'questions_en.js', varName: 'TRANSLATIONS_EN', langKey: 'en' },
  { file: 'questions_fr.js', varName: 'TRANSLATIONS_FR', langKey: 'fr' },
  { file: 'questions_es.js', varName: 'TRANSLATIONS_ES', langKey: 'es' },
  { file: 'questions_ar.js', varName: 'TRANSLATIONS_AR', langKey: 'ar' },
  { file: 'questions_am.js', varName: 'TRANSLATIONS_AM', langKey: 'am' }
];

for (const t of translationFiles) {
  console.log('Loading ' + t.file + ' ...');
  const dict = loadAsVar(t.file, t.varName);
  if (!dict) continue;
  keys[t.langKey] = {};
  let count = 0;
  for (const idStr of Object.keys(dict)) {
    const id = Number(idStr);
    const entry = dict[idStr];
    if (!entry || typeof entry.ci !== 'number') continue;
    const correct = decodeCI(entry.ci, id);
    if (correct < 0 || correct > 9) continue;
    keys[t.langKey][id] = correct;
    count++;
  }
  console.log('  ' + t.langKey + ' entries: ' + count);
}

// === Emit Apps Script file ===
const out = [];
out.push('// © 2026 Vitaly Gitelman. All Rights Reserved.');
out.push('// =============================================================================');
out.push('// answer_key.gs — Server-side answer key for exam score verification.');
out.push('// AUTO-GENERATED by deployment/generate_answer_key.js — do not edit by hand.');
out.push('// Generated: ' + new Date().toISOString());
out.push('// =============================================================================');
out.push('');
out.push('var ANSWER_KEY_BY_LANG = {');
const langs = Object.keys(keys);
for (let li = 0; li < langs.length; li++) {
  const lang = langs[li];
  const ids = Object.keys(keys[lang]).map(Number).sort((a, b) => a - b);
  if (ids.length === 0) {
    out.push('  ' + JSON.stringify(lang) + ': {}' + (li === langs.length - 1 ? '' : ','));
    continue;
  }
  // Compact one-id-per-comma format, wrapped at ~120 chars per line
  out.push('  ' + JSON.stringify(lang) + ': {');
  let line = '    ';
  for (let ki = 0; ki < ids.length; ki++) {
    const id = ids[ki];
    const entry = id + ':' + keys[lang][id] + (ki === ids.length - 1 ? '' : ',');
    if (line.length + entry.length > 118) {
      out.push(line);
      line = '    ' + entry;
    } else {
      line += entry;
    }
  }
  if (line.trim()) out.push(line);
  out.push('  }' + (li === langs.length - 1 ? '' : ','));
}
out.push('};');
out.push('');
out.push('// Lookup helper: returns the original (unshuffled) correct answer index for a');
out.push('// given question id and language, or null if not found. Falls back to Hebrew if');
out.push('// the requested language has no entry for this question.');
out.push('function lookupCorrectIndex(qId, language) {');
out.push('  var lang = language || "he";');
out.push('  var byLang = ANSWER_KEY_BY_LANG[lang];');
out.push('  if (byLang && byLang.hasOwnProperty(qId)) return byLang[qId];');
out.push('  var heLang = ANSWER_KEY_BY_LANG["he"];');
out.push('  if (heLang && heLang.hasOwnProperty(qId)) return heLang[qId];');
out.push('  return null;');
out.push('}');
out.push('');

const outPath = path.join(__dirname, 'answer_key.gs');
fs.writeFileSync(outPath, out.join('\n'), 'utf8');
const sizeKB = (fs.statSync(outPath).size / 1024).toFixed(1);
console.log('\nWrote ' + outPath + ' (' + sizeKB + ' KB)');
console.log('Languages: ' + langs.join(', '));
console.log('\nNext step: copy answer_key.gs into your Apps Script project as a new file.');
